### ISSUE TITLE
Parser does not get the correct length of translation vectors

### ISSUE THREAD

**Issue by akvatol** [tilde-lab/pycrystal#19]
The parser has a limitation on the length of the translation vectors of 50 angstroms, making serious difficulties in case one-dimensional objects when the vector a length can exceed this value. Can you fix it?

**Comment by blokhin** [comment]
@akvatol could you suggest some new meaningful value of the `CRYSTOUT.PERIODIC_LIMIT` meeting the needs of your case and the cases similar to yours? Please note, that the modeling engine formally assigns 500 angstroms to the non-periodic dimension(s) e.g. for a slab or polymer.

**Comment by akvatol** [comment]
In my case, the length of the translation vector does not exceed 250 angstroms. I think the limit of 300 angstroms will be sufficient.

**Comment by blokhin** [comment]
@akvatol please check if your issue is now resolved.

**Comment by akvatol** [comment]
Thanks, it works well!
